# DBMS setup
# Data Source

spring :
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/bootDB
    username : root
    password : '!Korea8080'

  # Use Option
  # create
  # create-drop
  # none
  # validate
  jpa.hibernate.ddl-auto : update

  thymeleaf :
    prefix : classpath:html/
    suffix : .html
    mode : HTML5
    template-resolver-order : 0
    cache : false
  
  # css, js, image
  web :
    resources :
      static-locations : classpath:static/
      add-mappings : true

  mvc :
    static-path-pattern : /static/**

  # logback-local.xml ??? ????? ????
logging :
  config : classpath:log/logback-local.xml